---

sudo: required
services:
  - docker
before_install:
  - docker build -t react-app-image -f Dockerfile.dev .

script:
  - docker run -e CI=true react-app-image npm run test

deploy:
  ende: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-app'
  env: 'DockerApp-env'
  bucket_name: 'elasticbeanstalk-us-east-2-142071238728'
  bucket_path: 'docker-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY